### ISSUE TITLE
Replace Bike Triangle Control with Simpler Element

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/otp.js#59]
I have a few issues with it. 
- Multiple issues with development — This is not the first time that intermingling Backbone, Bootstrap, and BTC has been an issue.
- Wow factor vs Usefulness — How precise does each factor need to be in reality? How often is this used? People will "miss it" but with a valid replacement we should be able to get the same effect.
- Raphael.js — No other part of OTP.js uses it. It's not massive, but it's ~1/6th the library size. It also requires major domain knowledge not needed anywhere else in this library.

**Proposal**: Create a dropdown with 7 stock named configurations.

Cycling Preference:
1. Quick
2. Flat
3. Friendly
4. Middle
5. Friendly + Flat
6. Friendly + Quick
7. Flat + Quick

Thoughts? @demory @abyrd @buma

**Comment by abyrd** [comment]
I have generally not questioned the bike triangle because it's existed since before OTP (if I'm not mistaken) and was a major selling point for TriMet. Apparently it is something that audiences really liked in OTP, and it conveyed OTP's nature as a flexible multi-modal router that was significantly different than other software.

On the technical side it’s actually somewhat awkward to represent three factors an affine combination, and it's true that the level of precision is not necessary. A simple list of presets makes sense to me, but I don't want to underestimate the appeal of the triangle.

The most important argument here is probably the inclusion of a library for one custom UI element that interferes with other frameworks in use. This is also problematic from a maintenance perspective. But don't we also need Raphael for the elevation chart?

**Comment by buma** [comment]
I also like current triangle.

One solution would be to remove Raphael from BikeTriangle and animate SVG with Javascript. Since Triangle SVG is always the same. The only thing that changes is when you move a circle rectangles change shape which shouldn't be hard to animate with Javascript.

But Raphael is still used in elevation chart like @abyrd said.
We could replaced it there with D3 but I'm not sure it would be much better.

**Comment by trevorgerhardt** [comment]
Ah. Didn't realize that the elevation chart used Raphael. But I am more familiar with D3 than Raphael, which is still under active development and more appropriate for charting in 2015.

I guess a similar question could be asked for the elevation chart. Would a table be able to accomplish the same thing a graph would? Is that level of detail necessary? 

Even deeper, these questions come from a desire to keep the library simple, make the core even more simple, and split out complicated features and graphics into separate libraries and plugins.

There's a lot of we could do with this interface, but there should be core features that are simple, easy to understand, and available to use and build on. The BTC and elevation charts in their current states are excessive beyond that, but understandably desirable in certain applications.

**Comment by abyrd** [comment]
I like Marko's approach to this: D3 is a seriously heavyweight tool though, and may add unnecessary complexity.

**Comment by abyrd** [comment]
I like Marko's approach to this: making an initial SVG that is then directly modified in code. There is probably no need for a complicated library to do that.

For the elevation chart, I think a visual representation is much better than a table. It's very nice to mouse-over the display and see where the points are along the route. I see no problem with switching to another library or no library though.

D3 is a serious tool that imposes a powerful but somewhat arcane data flow. Are we sure this is even necessary? Is there any problem with just drawing directly on a canvas using plain JS code?

**Comment by trevorgerhardt** [comment]
Mainly I was exploring making anything that does SVG rendering or charting an outside component. OTP.js is a form, narrative direction explanation, and map. With Leaflet, Backbone, and Bootstrap we're able to utilize a lot out of the box to make those parts easier to create and maintain. Anything more complicated (like SVG rendering controls, elevation charts) should be enabled by OTP.js but probably not contained inside of it.

If we're making the switch to make this the default, I think a more modular approach like this would help the long term life of this library.
