### ISSUE TITLE
Use icon rather than text for language chooser

### ISSUE THREAD

**Issue by abyrd** [conveyal/otp.js#68]
There are a lot of good choices here: 
https://thenounproject.com/term/translation/

I like the icons that have only two different characters with no decoration, like https://thenounproject.com/term/translation/7368/ and https://thenounproject.com/term/translation/41100/

The following one is also good and is CC0 so would not require extra attribution:
https://thenounproject.com/term/translation/987/

**Comment by buma** [comment]
Here are the results of adding translation icon to OTP.js.:
I resize the icon to 32x32 since this seems to be the height of row in UI.

This is https://thenounproject.com/term/translation/987/ icon
![old_icon](https://cloud.githubusercontent.com/assets/1055967/9005433/76d75524-377e-11e5-981d-75fe4c8f3040.png)

IMHO it is too small.

https://thenounproject.com/term/translation/7368/ is better:

![new_icon](https://cloud.githubusercontent.com/assets/1055967/9005434/76d804c4-377e-11e5-8f6a-adb74e51922e.png)

But looks strange with attribution at the bottom.

If attribution is removed it looks very nice:
![new_icon1](https://cloud.githubusercontent.com/assets/1055967/9005435/76d8c38c-377e-11e5-8877-22f0271291cf.png)

Price of icon is 2$.

**Comment by abyrd** [comment]
Agreed, the simpler icon is better. I like the concept of that one, but the execution not so much. It would be better if either the "wen" character was either slightly separated from the "A" character, or if the two were truly merged (the last stroke of "wen" continued smoothly into the A cross-bar, and they were the same width). The current form is neither here nor there. I bet I can make our own royalty-free icon in a few minutes.

**Comment by buma** [comment]
Yes. Icon seems easy enough to create. [here](https://github.com/buma/otp.js/tree/selectLanguageIcon) is a branch in which I tested them.

**Comment by abyrd** [comment]
I find it looks better when I don't try to create any continuity between the cross stroke of the A and the wen: ![language](https://cloud.githubusercontent.com/assets/112871/9005747/0cff0e96-3781-11e5-9a16-99d72ae14c18.png)

**Comment by abyrd** [comment]
By the way I place the above image into the public domain :) I guess I need to check the license on the font.
